name: Lint

on:
  push:
    branches: [main]
  pull_request:
    # This means run on all PRs.

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python
        run: uv python install

      - name: Lint/Check format with Ruff
        run: make lint-ci

      - name: Check formatting with Ruff
        run: make format-ci
